### PR TITLE
enables using `res.json` with openapi-enforcer-middleware validation

### PR DESCRIPTION
**Pull request by thurt**
see byu-oit/openapi-enforcer-middleware#6

### CODE REVIEW

**Comment by thurt** [comment]
failing test
```
  1) openapi-enforcer-middleware
       run controllers
         can handle date response for body when no schema:

      AssertionError: expected '2000-01-02T03:04:05.678Z' to equal '"2000-01-02T03:04:05.678Z"'
      + expected - actual

      -2000-01-02T03:04:05.678Z
      +"2000-01-02T03:04:05.678Z"
      
      at Context.it (test/index.test.js:457:27)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by thurt** [comment]
im not sure this test is even valid. it seems odd to have two sets of quotes around the date string

**Comment by Gi60s** [comment]
Thanks for the PR, but this fix will not work in all situations. JSON.stringify is capable of serializing some values that it cannot properly deserialize with JSON.parse.

The date object for example is serialized to an ISO date string, but when parsed is not converted back into a date object.

I have an idea that should make this work. I'll try it out.

**Comment by Gi60s** [comment]
I've made changes to this package and the peer dependency `openapi-enforcer` that should have this issue fixed. Update to `openapi-enforcer@1.2.1` and `openapi-enforcer-middleware@1.0.8`.

Your example from issue #6 should work now with `send`.

```js
const message = await Message.create({
  text: req.body.text,
  userId: req.user.id
});
res.send({ message });
```

**Pull request closed without merging**
